# Generated by Django 2.1.5 on 2019-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_auto_20190120_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(blank=True, default='abc', max_length=120, null=True),
        ),
    ]
