# Generated by Django 2.1.5 on 2019-01-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_auto_20190120_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
