# Generated by Django 2.1.5 on 2019-01-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20190120_1927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('email', 'ref_id')},
        ),
    ]
