# Generated by Django 2.1.5 on 2019-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0008_auto_20190120_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
